# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 23:43
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('glass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glassimage',
            name='thumb',
        ),
        migrations.AddField(
            model_name='glassimage',
            name='220x220',
            field=image_cropping.fields.ImageCropField(default='default_value', upload_to=b'', verbose_name='image'),
            preserve_default=False,
        ),
    ]
