# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glass', '0002_auto_20160223_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glassimage',
            name='220x220',
        ),
        migrations.AddField(
            model_name='glassimage',
            name='thumb',
            field=models.ImageField(default=None, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
