# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glass', '0003_auto_20160223_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glassimage',
            name='thumb',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
