# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glass', '0005_auto_20160223_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glassimage',
            name='thumb',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
