# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glass', '0006_auto_20160223_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glass',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
