# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160213_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default=None),
        ),
    ]
