# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='artwork',
            name='thumb',
            field=sorl.thumbnail.fields.ImageField(default=None, null=True, upload_to='photos/thumbs/'),
        ),
        migrations.AddField(
            model_name='artworkimage',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artworks.Artwork'),
        ),
    ]
