# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 22:41
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20160217_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='thumb',
            field=sorl.thumbnail.fields.ImageField(default='no thumbnail yet', null=True, upload_to='photos/thumbs/'),
        ),
    ]
