# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_auto_20160217_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='thumb',
        ),
        migrations.AddField(
            model_name='artwork',
            name='exhibited',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='materials',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='measures',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
